### ISSUE TITLE
This no longer seems to work when using activesupport from RailsLTS

### ISSUE THREAD

**Issue by severin** [rails-lts/json_cve_2020_10663#3]
Hey there,

I wanted to use this gem to fix the CVE in a old codebase that uses RailsLTS 4.2 on ruby 2.7. It seems that this gem is incompatible with the kwargs handling fix for `JSON.parse` that was added to RailsLTS 4.2.

Unfortunately I don't really understand why it is not working (my guess, it has something to do with the inteplay of `*args` and `**kwargs` in the method signatures).

Steps to reproduce:

1. Create a new Rails app with RailsLTS 4.2 running on ruby 2.7
2. Add this gem

-> The verification described in the README fails, but there is no error. 

Since this seems to fail silently there could be people using this gem assuming that they are not vulnerable to the CVE anymore but in fact they still are, so I think it would be best to either add a disclaimer to this repo or fix the issue.

**Comment by kratob** [comment]
Thanks for the report. We're looking into it and will try to get this fixed quickly.

**Comment by kratob** [comment]
Hi @severin,

This turned out not to be an issue in this gem, but an issue in Rails 4.2 LTS itself. We have released a new version and sent out communication via our mailing list.

Thanks again for bringing this to our attention. We were not sure if you would have wanted to be credited by name, but if you do, I will add credit to our changelogs, just let us know.

**Comment by severin** [comment]
Thanks for looking into this so promptly!

> We were not sure if you would have wanted to be credited by name, but if you do, I will add credit to our changelogs, just let us know.

Please do however you do normally: if you credit people by default then credit me, if you don't then I don't insist on it.

**Comment by kratob** [comment]
You're very welcome. I've added the credit. :-)
